name: "latest_net_G_B"
backend: "onnxruntime"
max_batch_size: 1

input {
  name: "input"
  data_type: TYPE_FP32
  dims: [ 3, 224, 224 ]
}

output {
  name: "output"
  data_type: TYPE_FP32
  dims: [ 3, 224, 224 ]
}

instance_group [
  {
    kind: KIND_GPU
    gpus: [ 0 ]
    count: 1
  }
]
